### ISSUE TITLE
IE에서 오류가....;ㅅ;

### ISSUE THREAD

**Issue by loveghn** [AstronautSion/DailyPopup#1]
팝업이 아예 출력이 안되는데 ...

// overlay 초기화
    _initOverlay : function(){
        var bool = false;
        var result = [];
        for( el of this.popupItems ){
            if(!el.classList.contains('is-pc') ){ result.push(el); }
        }
        for( item of result ){
            if(item.style.display == 'block' ){bool = true;}
        }
        bool == true ? this.overlay.style.display = 'block' : this.overlay.style.display = 'none';
    },

주석처리하면 출력이 잘 되더라구요. 이유가 뭘까여?
제 짧은 식견으론 querySelectorAll 이거때문인거같기도하고...

**Comment by AstronautSion** [comment]
잘지내시죠? 이걸 지금 확인하다니 레전드...
 IE 문제는 아니고 addEventListener안에 this문제였어요 
 수정해서 커밋했습니다 제보 감사합니다 :)
